name: Testing The Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - ndMeTTa

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: This Set up Node.js environment
              uses: actions/setup-node@v3
              with:
                node-version: '16'
                cache: 'npm'

            - name: This Install all needed dependencies
              run: npm install

            - name: This Run the tests
              run: npm test